---
name: Test against downstream projects

on:
  workflow_dispatch:

jobs:
  starlette:
    name: "Starlette on Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: encode/starlette
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          allow-prereleases: true
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          scripts/install
          pip install anyio@git+https://github.com/agronholm/anyio.git@${{ github.ref_name }}
      - name: Run tests
        run: scripts/test
      - name: Enforce coverage
        run: scripts/coverage

  httpcore:
    name: "Httpcore on Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: encode/httpcore
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          allow-prereleases: true
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          scripts/install
          pip install anyio@git+https://github.com/agronholm/anyio.git@${{ github.ref_name }}
      - name: Run tests
        run: scripts/test
      - name: Enforce coverage
        run: scripts/coverage
